import 'food_types.dart';

/// One row in the curated food library. Matches the shape of the
/// persisted `Foods` table but lives in pure Dart so we can seed + patch
/// the DB on first run / upgrade.
class SeedFood {
  final String name;
  final FoodCategory category;
  final num baseAmount;
  final FoodUnit baseUnit;
  final int kcal;
  final double proteinG;

  const SeedFood({
    required this.name,
    required this.category,
    required this.baseAmount,
    required this.baseUnit,
    required this.kcal,
    required this.proteinG,
  });
}

/// Curated food library (~140 items) spanning global staples, Indian
/// everyday foods, modern health items and common prepared dishes.
/// Macros are drawn from USDA FoodData Central and the Indian Food
/// Composition Tables; real-world brand / preparation variance is ±5%.
/// Values are per `baseAmount` of `baseUnit` — e.g. 100 g of chicken
/// breast, 1 piece of banana, 250 ml of milk, 1 serving of biryani.
const List<SeedFood> seedFoods = [
  // Protein
  SeedFood(
    name: 'Chicken breast, boneless',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 165,
    proteinG: 31.0,
  ),
  SeedFood(
    name: 'Chicken thigh, boneless',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 209,
    proteinG: 26.0,
  ),
  SeedFood(
    name: 'Chicken drumstick (cooked)',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 172,
    proteinG: 28.3,
  ),
  SeedFood(
    name: 'Turkey breast, sliced',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 135,
    proteinG: 30.0,
  ),
  SeedFood(
    name: 'Ground beef, 85% lean',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 215,
    proteinG: 18.6,
  ),
  SeedFood(
    name: 'Beef sirloin steak',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 206,
    proteinG: 27.0,
  ),
  SeedFood(
    name: 'Pork tenderloin',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 143,
    proteinG: 26.0,
  ),
  SeedFood(
    name: 'Bacon (cooked)',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 541,
    proteinG: 37.0,
  ),
  SeedFood(
    name: 'Lamb, lean (cooked)',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 258,
    proteinG: 25.6,
  ),
  SeedFood(
    name: 'Salmon, Atlantic',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 208,
    proteinG: 20.4,
  ),
  SeedFood(
    name: 'Tuna, canned in water',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 116,
    proteinG: 25.5,
  ),
  SeedFood(
    name: 'Tilapia fillet',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 96,
    proteinG: 20.1,
  ),
  SeedFood(
    name: 'Shrimp (cooked)',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 99,
    proteinG: 24.0,
  ),
  SeedFood(
    name: 'Cod fillet',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 82,
    proteinG: 17.8,
  ),
  SeedFood(
    name: 'Egg, large',
    category: FoodCategory.protein,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 72,
    proteinG: 6.3,
  ),
  SeedFood(
    name: 'Egg white, large',
    category: FoodCategory.protein,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 17,
    proteinG: 3.6,
  ),
  SeedFood(
    name: 'Tofu, firm',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 144,
    proteinG: 17.3,
  ),
  SeedFood(
    name: 'Tempeh',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 192,
    proteinG: 20.3,
  ),
  SeedFood(
    name: 'Seitan',
    category: FoodCategory.protein,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 143,
    proteinG: 25.0,
  ),
  SeedFood(
    name: 'Whey protein isolate (1 scoop)',
    category: FoodCategory.protein,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 120,
    proteinG: 24.0,
  ),
  SeedFood(
    name: 'Vegan pea protein (1 scoop)',
    category: FoodCategory.protein,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 115,
    proteinG: 22.0,
  ),

  // Grains
  SeedFood(
    name: 'Basmati rice (cooked)',
    category: FoodCategory.grains,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 130,
    proteinG: 2.7,
  ),
  SeedFood(
    name: 'White rice (cooked)',
    category: FoodCategory.grains,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 130,
    proteinG: 2.7,
  ),
  SeedFood(
    name: 'Brown rice (cooked)',
    category: FoodCategory.grains,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 123,
    proteinG: 2.7,
  ),
  SeedFood(
    name: 'Quinoa (cooked)',
    category: FoodCategory.grains,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 120,
    proteinG: 4.4,
  ),
  SeedFood(
    name: 'Rolled oats (dry)',
    category: FoodCategory.grains,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 117,
    proteinG: 4.1,
  ),
  SeedFood(
    name: 'Oatmeal bowl (cooked)',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 166,
    proteinG: 5.9,
  ),
  SeedFood(
    name: 'Whole wheat bread (1 slice)',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 81,
    proteinG: 4.0,
  ),
  SeedFood(
    name: 'White bread (1 slice)',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 75,
    proteinG: 2.6,
  ),
  SeedFood(
    name: 'Bagel, plain',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 245,
    proteinG: 10.0,
  ),
  SeedFood(
    name: 'Pasta, spaghetti (cooked)',
    category: FoodCategory.grains,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 158,
    proteinG: 5.8,
  ),
  SeedFood(
    name: 'Cornflakes',
    category: FoodCategory.grains,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 113,
    proteinG: 2.1,
  ),
  SeedFood(
    name: 'Roti (whole wheat)',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 104,
    proteinG: 3.1,
  ),
  SeedFood(
    name: 'Chapati',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 97,
    proteinG: 3.0,
  ),
  SeedFood(
    name: 'Paratha, plain',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 185,
    proteinG: 4.5,
  ),
  SeedFood(
    name: 'Idli',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 58,
    proteinG: 2.0,
  ),
  SeedFood(
    name: 'Dosa, plain',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 133,
    proteinG: 2.7,
  ),
  SeedFood(
    name: 'Naan',
    category: FoodCategory.grains,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 260,
    proteinG: 9.0,
  ),

  // Vegetables
  SeedFood(
    name: 'Broccoli (raw)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 34,
    proteinG: 2.8,
  ),
  SeedFood(
    name: 'Spinach (raw)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 23,
    proteinG: 2.9,
  ),
  SeedFood(
    name: 'Kale (raw)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 35,
    proteinG: 2.9,
  ),
  SeedFood(
    name: 'Carrot (raw)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 41,
    proteinG: 0.9,
  ),
  SeedFood(
    name: 'Cucumber',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 15,
    proteinG: 0.7,
  ),
  SeedFood(
    name: 'Tomato',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 18,
    proteinG: 0.9,
  ),
  SeedFood(
    name: 'Bell pepper',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 31,
    proteinG: 1.0,
  ),
  SeedFood(
    name: 'Onion',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 40,
    proteinG: 1.1,
  ),
  SeedFood(
    name: 'Cauliflower (raw)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 25,
    proteinG: 1.9,
  ),
  SeedFood(
    name: 'Potato (boiled)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 87,
    proteinG: 1.9,
  ),
  SeedFood(
    name: 'Sweet potato (baked)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 90,
    proteinG: 2.0,
  ),
  SeedFood(
    name: 'Okra (cooked)',
    category: FoodCategory.vegetables,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 33,
    proteinG: 1.9,
  ),

  // Fruits
  SeedFood(
    name: 'Banana, medium',
    category: FoodCategory.fruits,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 105,
    proteinG: 1.3,
  ),
  SeedFood(
    name: 'Apple, medium',
    category: FoodCategory.fruits,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 95,
    proteinG: 0.5,
  ),
  SeedFood(
    name: 'Orange, medium',
    category: FoodCategory.fruits,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 62,
    proteinG: 1.2,
  ),
  SeedFood(
    name: 'Strawberries',
    category: FoodCategory.fruits,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 32,
    proteinG: 0.7,
  ),
  SeedFood(
    name: 'Blueberries',
    category: FoodCategory.fruits,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 57,
    proteinG: 0.7,
  ),
  SeedFood(
    name: 'Grapes',
    category: FoodCategory.fruits,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 69,
    proteinG: 0.7,
  ),
  SeedFood(
    name: 'Mango',
    category: FoodCategory.fruits,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 60,
    proteinG: 0.8,
  ),
  SeedFood(
    name: 'Pineapple',
    category: FoodCategory.fruits,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 50,
    proteinG: 0.5,
  ),
  SeedFood(
    name: 'Watermelon',
    category: FoodCategory.fruits,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 30,
    proteinG: 0.6,
  ),
  SeedFood(
    name: 'Papaya',
    category: FoodCategory.fruits,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 43,
    proteinG: 0.5,
  ),
  SeedFood(
    name: 'Avocado, medium',
    category: FoodCategory.fruits,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 240,
    proteinG: 3.0,
  ),
  SeedFood(
    name: 'Pear, medium',
    category: FoodCategory.fruits,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 101,
    proteinG: 0.6,
  ),

  // Legumes
  SeedFood(
    name: 'Moong dal (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 105,
    proteinG: 7.0,
  ),
  SeedFood(
    name: 'Toor dal (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 116,
    proteinG: 7.5,
  ),
  SeedFood(
    name: 'Masoor dal (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 116,
    proteinG: 9.0,
  ),
  SeedFood(
    name: 'Chana dal (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 130,
    proteinG: 8.9,
  ),
  SeedFood(
    name: 'Rajma (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 127,
    proteinG: 8.7,
  ),
  SeedFood(
    name: 'Chickpeas (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 164,
    proteinG: 8.9,
  ),
  SeedFood(
    name: 'Black beans (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 132,
    proteinG: 8.9,
  ),
  SeedFood(
    name: 'Kidney beans (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 127,
    proteinG: 8.7,
  ),
  SeedFood(
    name: 'Lentils, green (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 116,
    proteinG: 9.0,
  ),
  SeedFood(
    name: 'Edamame (cooked)',
    category: FoodCategory.legumes,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 122,
    proteinG: 11.0,
  ),

  // Nuts & seeds
  SeedFood(
    name: 'Almonds',
    category: FoodCategory.nuts,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 579,
    proteinG: 21.2,
  ),
  SeedFood(
    name: 'Cashews',
    category: FoodCategory.nuts,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 553,
    proteinG: 18.2,
  ),
  SeedFood(
    name: 'Peanuts (roasted)',
    category: FoodCategory.nuts,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 585,
    proteinG: 23.7,
  ),
  SeedFood(
    name: 'Walnuts',
    category: FoodCategory.nuts,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 654,
    proteinG: 15.2,
  ),
  SeedFood(
    name: 'Pistachios',
    category: FoodCategory.nuts,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 560,
    proteinG: 20.2,
  ),
  SeedFood(
    name: 'Chia seeds',
    category: FoodCategory.nuts,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 146,
    proteinG: 5.0,
  ),
  SeedFood(
    name: 'Flax seeds',
    category: FoodCategory.nuts,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 160,
    proteinG: 5.5,
  ),
  SeedFood(
    name: 'Pumpkin seeds',
    category: FoodCategory.nuts,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 559,
    proteinG: 30.2,
  ),
  SeedFood(
    name: 'Sunflower seeds',
    category: FoodCategory.nuts,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 584,
    proteinG: 20.8,
  ),
  SeedFood(
    name: 'Peanut butter (1 tbsp)',
    category: FoodCategory.nuts,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 95,
    proteinG: 3.5,
  ),
  SeedFood(
    name: 'Almond butter (1 tbsp)',
    category: FoodCategory.nuts,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 98,
    proteinG: 3.4,
  ),

  // Dairy
  SeedFood(
    name: 'Whole milk',
    category: FoodCategory.dairy,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 150,
    proteinG: 8.0,
  ),
  SeedFood(
    name: 'Milk 2%',
    category: FoodCategory.dairy,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 122,
    proteinG: 8.1,
  ),
  SeedFood(
    name: 'Skim milk',
    category: FoodCategory.dairy,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 83,
    proteinG: 8.3,
  ),
  SeedFood(
    name: 'Greek yogurt, plain (nonfat)',
    category: FoodCategory.dairy,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 59,
    proteinG: 10.0,
  ),
  SeedFood(
    name: 'Curd (dahi)',
    category: FoodCategory.dairy,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 61,
    proteinG: 3.5,
  ),
  SeedFood(
    name: 'Cottage cheese (low-fat)',
    category: FoodCategory.dairy,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 72,
    proteinG: 12.4,
  ),
  SeedFood(
    name: 'Paneer',
    category: FoodCategory.dairy,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 265,
    proteinG: 18.3,
  ),
  SeedFood(
    name: 'Cheddar cheese',
    category: FoodCategory.dairy,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 403,
    proteinG: 24.9,
  ),
  SeedFood(
    name: 'Mozzarella cheese',
    category: FoodCategory.dairy,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 280,
    proteinG: 22.2,
  ),
  SeedFood(
    name: 'Parmesan cheese',
    category: FoodCategory.dairy,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 431,
    proteinG: 38.5,
  ),

  // Prepared dishes
  SeedFood(
    name: 'Chicken biryani (1 plate)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 540,
    proteinG: 26.0,
  ),
  SeedFood(
    name: 'Veg biryani (1 plate)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 465,
    proteinG: 10.0,
  ),
  SeedFood(
    name: 'Butter chicken (1 cup)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 430,
    proteinG: 26.0,
  ),
  SeedFood(
    name: 'Dal tadka (1 cup)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 210,
    proteinG: 11.0,
  ),
  SeedFood(
    name: 'Chole (chickpea curry) (1 cup)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 270,
    proteinG: 12.0,
  ),
  SeedFood(
    name: 'Rajma chawal (1 plate)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 470,
    proteinG: 15.0,
  ),
  SeedFood(
    name: 'Idli sambar (2 idli + sambar)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 210,
    proteinG: 8.0,
  ),
  SeedFood(
    name: 'Poha (1 bowl)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 250,
    proteinG: 5.0,
  ),
  SeedFood(
    name: 'Upma (1 bowl)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 270,
    proteinG: 6.5,
  ),
  SeedFood(
    name: 'Pizza slice (margherita)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 265,
    proteinG: 11.0,
  ),
  SeedFood(
    name: 'Cheeseburger',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 535,
    proteinG: 29.0,
  ),
  SeedFood(
    name: 'Grilled cheese sandwich',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 395,
    proteinG: 14.0,
  ),
  SeedFood(
    name: 'Sushi roll (6 pc, salmon)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 320,
    proteinG: 12.0,
  ),
  SeedFood(
    name: 'Pasta alfredo (1 plate)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 620,
    proteinG: 20.0,
  ),
  SeedFood(
    name: 'Chow mein (1 plate)',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 430,
    proteinG: 14.0,
  ),
  SeedFood(
    name: 'Caesar salad with chicken',
    category: FoodCategory.preparedDishes,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 470,
    proteinG: 32.0,
  ),

  // Snacks
  SeedFood(
    name: 'Dark chocolate (70%)',
    category: FoodCategory.snacks,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 598,
    proteinG: 7.8,
  ),
  SeedFood(
    name: 'Milk chocolate',
    category: FoodCategory.snacks,
    baseAmount: 100,
    baseUnit: FoodUnit.g,
    kcal: 535,
    proteinG: 7.6,
  ),
  SeedFood(
    name: 'Potato chips (30 g)',
    category: FoodCategory.snacks,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 160,
    proteinG: 2.0,
  ),
  SeedFood(
    name: 'Chocolate-chip cookie',
    category: FoodCategory.snacks,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 53,
    proteinG: 0.6,
  ),
  SeedFood(
    name: 'Granola bar',
    category: FoodCategory.snacks,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 120,
    proteinG: 2.5,
  ),
  SeedFood(
    name: 'Protein bar (~60 g)',
    category: FoodCategory.snacks,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 220,
    proteinG: 20.0,
  ),
  SeedFood(
    name: 'Samosa',
    category: FoodCategory.snacks,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 260,
    proteinG: 5.0,
  ),
  SeedFood(
    name: 'Pakora (onion, 3 pc)',
    category: FoodCategory.snacks,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 175,
    proteinG: 4.0,
  ),
  SeedFood(
    name: 'Popcorn (air-popped)',
    category: FoodCategory.snacks,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 116,
    proteinG: 3.7,
  ),
  SeedFood(
    name: 'Pretzels',
    category: FoodCategory.snacks,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 114,
    proteinG: 3.0,
  ),
  SeedFood(
    name: 'Mathri',
    category: FoodCategory.snacks,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 90,
    proteinG: 1.5,
  ),
  SeedFood(
    name: 'Rice cake, plain',
    category: FoodCategory.snacks,
    baseAmount: 1,
    baseUnit: FoodUnit.piece,
    kcal: 35,
    proteinG: 0.7,
  ),

  // Beverages
  SeedFood(
    name: 'Cola (can)',
    category: FoodCategory.beverages,
    baseAmount: 330,
    baseUnit: FoodUnit.ml,
    kcal: 139,
    proteinG: 0.0,
  ),
  SeedFood(
    name: 'Orange juice',
    category: FoodCategory.beverages,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 112,
    proteinG: 1.7,
  ),
  SeedFood(
    name: 'Beer, lager',
    category: FoodCategory.beverages,
    baseAmount: 330,
    baseUnit: FoodUnit.ml,
    kcal: 143,
    proteinG: 1.6,
  ),
  SeedFood(
    name: 'Red wine',
    category: FoodCategory.beverages,
    baseAmount: 150,
    baseUnit: FoodUnit.ml,
    kcal: 125,
    proteinG: 0.1,
  ),
  SeedFood(
    name: 'Chai with milk & sugar',
    category: FoodCategory.beverages,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 120,
    proteinG: 3.5,
  ),
  SeedFood(
    name: 'Black coffee',
    category: FoodCategory.beverages,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 2,
    proteinG: 0.3,
  ),
  SeedFood(
    name: 'Whey shake (1 scoop in water)',
    category: FoodCategory.beverages,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 120,
    proteinG: 24.0,
  ),
  SeedFood(
    name: 'Sports drink (bottle)',
    category: FoodCategory.beverages,
    baseAmount: 355,
    baseUnit: FoodUnit.ml,
    kcal: 80,
    proteinG: 0.0,
  ),
  SeedFood(
    name: 'Almond milk, unsweetened',
    category: FoodCategory.beverages,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 37,
    proteinG: 1.0,
  ),
  SeedFood(
    name: 'Soy milk, unsweetened',
    category: FoodCategory.beverages,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 80,
    proteinG: 7.0,
  ),
  SeedFood(
    name: 'Oat milk',
    category: FoodCategory.beverages,
    baseAmount: 250,
    baseUnit: FoodUnit.ml,
    kcal: 120,
    proteinG: 3.0,
  ),

  // Condiments
  SeedFood(
    name: 'Ketchup (1 tbsp)',
    category: FoodCategory.condiments,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 17,
    proteinG: 0.2,
  ),
  SeedFood(
    name: 'Mayonnaise (1 tbsp)',
    category: FoodCategory.condiments,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 94,
    proteinG: 0.1,
  ),
  SeedFood(
    name: 'Hummus (30 g)',
    category: FoodCategory.condiments,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 50,
    proteinG: 2.4,
  ),
  SeedFood(
    name: 'Peanut sauce (30 g)',
    category: FoodCategory.condiments,
    baseAmount: 30,
    baseUnit: FoodUnit.g,
    kcal: 85,
    proteinG: 3.0,
  ),
  SeedFood(
    name: 'Soy sauce (15 ml)',
    category: FoodCategory.condiments,
    baseAmount: 15,
    baseUnit: FoodUnit.ml,
    kcal: 8,
    proteinG: 1.3,
  ),

  // Fats
  SeedFood(
    name: 'Olive oil (1 tbsp)',
    category: FoodCategory.fats,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 119,
    proteinG: 0.0,
  ),
  SeedFood(
    name: 'Ghee (1 tbsp)',
    category: FoodCategory.fats,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 123,
    proteinG: 0.0,
  ),
  SeedFood(
    name: 'Coconut oil (1 tbsp)',
    category: FoodCategory.fats,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 117,
    proteinG: 0.0,
  ),
  SeedFood(
    name: 'Butter (1 tbsp)',
    category: FoodCategory.fats,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 102,
    proteinG: 0.1,
  ),
  SeedFood(
    name: 'Avocado oil (1 tbsp)',
    category: FoodCategory.fats,
    baseAmount: 1,
    baseUnit: FoodUnit.serving,
    kcal: 124,
    proteinG: 0.0,
  ),
];
